# Generated by Django 4.0.1 on 2022-01-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multistepform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='facebook',
            new_name='father',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='gplus',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='password',
            new_name='marrital',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='twitter',
            new_name='spouse',
        ),
    ]
